### ISSUE TITLE
TypeError: write_zip() got multiple values for argument 'story'

### ISSUE THREAD

**Issue by cyian-1756** [sexypants/chyoa-scraper#2]
When I run

`python3 -m chyoa download 'https://chyoa.com/story/Aaralon%27s-Discoveries.276' aaralons_discoveries.zip`

The program errors out with 

```python
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/username/code/chyoa-scraper/chyoa/__main__.py", line 13, in <module>
    chyoa.main(sys.argv)
  File "/home/username/code/chyoa-scraper/chyoa/__init__.py", line 36, in main
    dl.download(url, dest, debug=debug)
  File "/home/username/code/chyoa-scraper/chyoa/download.py", line 27, in download
    write_zip(story, dest, story=self.recursive)
TypeError: write_zip() got multiple values for argument 'story'
```

**Comment by sexypants** [comment]
Fixed in 9a6e991.
