### ISSUE TITLE
http.client.RemoteDisconnected: Remote end closed connection without response

### ISSUE THREAD

**Issue by cyian-1756** [sexypants/chyoa-scraper#5]
When I run `python3 -m chyoa download 'https://chyoa.com/story/Aaralon%27s-Discoveries.276' aaralons_discoveries` the program errors out with 

```python
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wil/code/chyoa-scraper/chyoa/__main__.py", line 13, in <module>
    chyoa.main(sys.argv)
  File "/home/wil/code/chyoa-scraper/chyoa/__init__.py", line 36, in main
    dl.download(url, dest, debug=debug)
  File "/home/wil/code/chyoa-scraper/chyoa/download.py", line 21, in download
    scraper.scrape(url)
  File "/home/wil/code/chyoa-scraper/chyoa/scraper.py", line 32, in scrape
    self._scrape_urls(self.to_visit)
  File "/home/wil/code/chyoa-scraper/chyoa/scraper.py", line 48, in _scrape_urls
    fields = self.parser.get_chapter_fields(url)
  File "/home/wil/code/chyoa-scraper/chyoa/parser.py", line 36, in get_chapter_fields
    response = urlopen(url)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by sexypants** [comment]
https://docs.python.org/3/library/http.client.html#http.client.RemoteDisconnected

This sounds like either a problem with CHYOA's servers. Maybe Cloudflare is rate limiting you?
